language: php
matrix:
  include:
    - php: 7.2
      env: DB=mysql
      addons:
        mariadb: '10.2'

sudo: false
before_install:
  - export NEOS_TARGET_VERSION=4.1
  - cd ..
  - git clone https://github.com/neos/neos-development-distribution.git -b ${NEOS_TARGET_VERSION}
  - cd neos-development-distribution
  - composer config repositories.contentrepository-development-collection git https://github.com/neos/contentrepository-development-collection.git
  - composer config repositories.content-repository-dimensionspace git https://github.com/neos/content-repository-dimensionspace
  - composer config minimum-stability dev
  - composer config prefer-stable true
  - composer require --no-update --no-interaction neos/event-sourcing:dev-master
  - composer require --no-update --no-interaction neos/neos-development-collection:"dev-event-sourced-patch as dev-master"
  - composer require --no-update --no-interaction neos/flow-development-collection:"dev-master"
  - composer require --no-update --no-interaction neos/neos-ui:"dev-event-sourced-patch as dev-master"
  - composer require --no-update --no-interaction neos/demo:"dev-master"
  - composer require --no-update --dev --no-interaction neos/behat:dev-master
  - composer require --no-update --dev --prefer-source --no-interaction flowpack/behat:dev-master
  - cat composer.json
install:
  - composer update --no-progress --no-interaction
  - composer install -d Build/Behat
  - cd ..
  - rm -rf neos-development-distribution/Packages/CR
  - mv contentrepository-development-collection neos-development-distribution/Packages/CR
  - cd neos-development-distribution
  - ./flow flow:package:rescan
before_script:
  - cp Configuration/Settings.yaml.example Configuration/Settings.yaml
  - Build/BuildEssentials/TravisCi/SetupDatabase.sh
  - cp Configuration/Settings.yaml Configuration/Testing/

script:
  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/CR/Neos.EventSourcedContentRepository/Tests/Functional
  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/CR/Neos.EventSourcedNeosAdjustments/Tests/Functional
  - bin/behat --ansi --stop-on-failure -f progress -c Packages/CR/Neos.EventSourcedContentRepository/Tests/Behavior/behat.yml.dist
  #- bin/behat --ansi --stop-on-failure -f progress -c Packages/CR/Neos.EventSourcedNeosAdjustments/Tests/Behavior/behat.yml.dist
