Neos:
  Flow:
    error:
      debugger:
        ignoredClasses:
          'Neos\\ContentGraph\\DoctrineDbalAdapter.*': true
  EventSourcing:
    EventStore:
      stores:
        'foo':
          listeners:
            'Neos\ContentGraph\DoctrineDbalAdapter\.*': true
