Neos:
  Flow:
    error:
      debugger:
        ignoredClasses:
          'Neos\\ContentGraph\\RedisGraphAdapter.*': true
  EventSourcing:
    EventStore:
      stores:
        'ContentRepository':
          listeners:
            'Neos\ContentGraph\RedisGraphAdapter\.*': true
